var shelters =[
{"ext_id":null,
"cat1":"Social Services",
"cat2":"Homeless Shelters and Services",
"cat3":null,
"org_name":"www.lbrm.org",
"Name":"Long Beach Rescue Mission",
"addrln1":"1335 Pacific Ave",
"addrln2":null,
"city":"Long Beach",
"state":"CA",
"hours":"Monday through Sunday, 24 hours per day. ",
"phones":"Service/Intake and Administration (562) 591-1292, Long Beach Multi-Service Center Service/Intake (562) 733-1147,  FAX (562) 216-7667",
"email":null,
"url":"www.lbrm.org",
"info1":null,
"info2":null,
"post_id":56479,
"description":"The agency provides emergency food, shelter, clothing, counsel, spiritually-based adult rehabilitation transitional housing programs.",
"zip":"90813"
},
{ 
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":"www.village-isa.org",
      "Name":"Mental Health America Of Los Angeles - Long Beach",
      "addrln1":"456 Elm Ave.",
      "addrln2":null,
      "city":"Long Beach",
      "state":"CA",
      "hours":"Monday through Friday, 9:00am to 5:00pm. ",
      "phones":"FAX (562) 437-5072,  Service/Intake (562) 437-6717",
      "email":null,
      "url":"www.village-isa.org",
      "info1":null,
      "info2":null,
      "post_id":57763,
      "description":"The agency provides homeless support services and mental health services for people in the Long Beach area.",
      "zip":"90802"
},
{ 
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":"www.womenshelterlb.com/",
      "Name":"Womenshelter Of Long Beach",
      "addrln1":"930 Pacific Ave.",
      "addrln2":null,
      "city":"Long Beach",
      "state":"CA",
      "hours":"Monday through Friday, 8:00am to 5:00pm. ",
      "phones":"Service/Intake and Administration (562) 437-7233,  FAX (562) 436-4943, 562) HER HOME - 24 hrs. Service/Intake and Hotline (562) 437-4663",
      "email":null,
      "url":"www.womenshelterlb.com/",
      "info1":null,
      "info2":null,
      "post_id":58152,
      "description":"The agency provides shelter and domestic violence services for victims of domestic violence and their children as well as volunteer opportunities for individuals living in Los Angeles County.",
      "zip":"90813",
   },
{  
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":"www.lahsa.org",
      "Name":"Year Round Pick-Up Site - Catholic Charities Community Center",
      "addrln1":"123 W 14Th St",
      "addrln2":null,
      "city":"Long Beach",
      "state":"CA",
      "hours":"Pick-up hours vary. ",
      "phones":"Service/Intake (323) 298-1316, Intake Service/Intake (562) 733-1147",
      "email":null,
      "url":"www.lahsa.org",
      "info1":null,
      "info2":null,
      "post_id":58177,
      "description":"The agency provides shelter, motel vouchers and transportation to homeless individuals and families.",
      "zip":"90813"
},
{  
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":"www.lahsa.org",
      "Name":"Year Round Pick-Up Site - Long Beach Multi-Service Center",
      "addrln1":"1301 W. 12th St.",
      "addrln2":null,
      "city":"Long Beach",
      "state":"CA",
      "hours":null,
      "phones":"Intake Service/Intake (562) 733-1147",
      "email":null,
      "url":"www.lahsa.org",
      "info1":null,
      "info2":null,
      "post_id":58179,
      "description":"The agency provides shelter, motel vouchers and transportation to homeless individuals and families.",
      "zip":"90813",
},
{ 
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":"www.sucasadv.org",
      "Name":"Su Casa - Ending Domestic Violence",
      "addrln1":"3840 Woodruff Ave.",
      "addrln2":"Administrative Office| Suite 203",
      "city":"Long Beach",
      "state":"CA",
      "hours":"Monday through Friday, 8:00am to 5:00pm. ",
      "phones":"Administrative (562) 421-6537,  FAX (562) 421-8117, 24-hour Hotline Service/Intake/Hotline (Voice/TDD) (562) 402-4888",
      "email":null,
      "url":"www.sucasadv.org",
      "info1":null,
      "info2":null,
      "post_id":58587,
      "description":"The center provides domestic violence services for people of all ages, including transgendered individuals, a shelter for battered persons and their children and volunteer opportunities.",
      "zip":"90808"
},
{ 
   "attributes":{ 
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":"www.catholiccharitiesla.org/sanpedro.html",
      "Name":"Catholic Charities Of Los Angeles - San Pedro Region - Long Beach Community Services Center",
      "addrln1":"123 E. 14th St.",
      "addrln2":null,
      "city":"Long Beach",
      "state":"CA",
      "hours":null,
      "phones":"Service/Intake and Administration (562) 591-1351,  Administrative (562) 591-1641",
      "email":null,
      "url":"www.catholiccharitiesla.org/sanpedro.html",
      "info1":null,
      "info2":null,
      "post_id":60044,
      "description":"The office administers a number of community centers and program offices within the San Pedro Pastoral Region, which extends from Palos Verdes to Pico Rivera on the north to Long Beach on the south.",
      "zip":"90813"
},
{ 
   "attributes":{ 
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":"www.COAlongbeach.org",
      "Name":"Christian Outreach In Action",
      "addrln1":"515 E. 3rd St.",
      "addrln2":null,
      "city":"Long Beach",
      "state":"CA",
      "hours":null,
      "phones":"Service/Intake and Administration (562) 432-1440,  FAX (562) 590-8984",
      "email":null,
      "url":"www.COAlongbeach.org",
      "info1":null,
      "info2":null,
      "post_id":60138,
      "description":"The organization provides emergency food, holiday assistance, homeless support services, personal goods and shelter for people who are in the Long Beach area, including people who are homeless.",
      "zip":"90802"
},
{ 
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":"www.COAlongbeach.org",
      "Name":"Christian Outreach In Action - Transitional Housing",
      "addrln1":"1950 Chestnut Ave.",
      "addrln2":null,
      "city":"Long Beach",
      "state":"CA",
      "hours":"Monday through Sunday, 24 hours per day. ",
      "phones":"Service/Intake (562) 432-1440",
      "email":null,
      "url":"www.COAlongbeach.org",
      "info1":null,
      "info2":null,
      "post_id":60139,
      "description":"The organization provides emergency food, holiday assistance, homeless support services, personal goods and shelter for people who are in the Long Beach area, including people who are homeless.",
      "zip":"90806"
},
{ 
  "ext_id":null,
  "cat1":"Social Services",
  "cat2":"Homeless Shelters and Services",
  "cat3":null,
  "org_name":"www.intervalhouse.org",
  "Name":"Interval House",
  "addrln1":"6615 E. Pacific Coast Highway",
  "addrln2":"Outreach Office| Suite 170",
  "city":"Long Beach",
  "state":"CA",
  "hours":"Monday through Sunday, 24 hours per day. ",
  "phones":"Administrative (562) 594-9492, L A County - 24 hours Service/Intake and Hotline (562) 594-4555",
  "email":null,
  "url":"www.intervalhouse.org",
  "info1":null,
  "info2":null,
  "post_id":60852,
  "description":"This agency provides domestic violence services, a battered women's shelter for battered women and their children and welfare-to-work support services to battered women who receive CalWORKs and live primarily in the Long Beach and the surrounding areas.",
  "zip":"90803"
},
{ 
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":null,
      "Name":"Long Beach Family Shelter For The Homeless",
      "addrln1":"Long Beach Family Shelter",
      "addrln2":null,
      "city":"Long Beach",
      "state":"CA",
      "hours":"Monday through Sunday, 24 hours per day. ",
      "phones":"People w/ Disabilities -  Disabled Resources Center Service/Intake (562) 427-1000, Catholic Charities Administration (562) 591-1351, Long Beach Multi-Service Center Service/Intake (562) 733-1147,  Administrative (562) 388-7670",
      "email":null,
      "url":null,
      "info1":null,
      "info2":null,
      "post_id":70297,
      "description":"The agency provides shelter for people of all ages in the Long Beach area, including families with children and people who have physical disabilities.",
      "groups": 
      "zip":"90813"
},
{ 
      "ext_id":null,
      "cat1":"Social Services",
      "cat2":"Homeless Shelters and Services",
      "cat3":null,
      "org_name":null,
      "Name":"Long Beach Rescue Mission - Lydia House Intake Site",
      "addrln1":"1301 W 12Th St",
      "addrln2":"Long Beach Multi-Service Center",
      "city":"Long Beach",
      "state":"CA",
      "hours":"Monday through Friday, 9:00am. ",
      "phones":null,
      "email":null,
      "url":"www.lbrm.org",
      "info1":null,
      "info2":null,
      "post_id":71888,
      "description":"The agency provides emergency food, shelter, clothing, counsel, spiritually-based adult rehabilitation transitional housing programs.",
      "zip":"90813",
   }
];

function lookUpShelter (name, prop){
  for(var i = 0; i < shelters.length; i++){
    if (shelters[i].Name === name){
      return shelters[i][prop]

    }
  }
  console.log("No such place")
}